# Generated by Django 4.1.7 on 2023-03-02 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_voluntarios', '0002_delete_voluntario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('es_atendida', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('es_asignado', models.CharField(default='0', max_length=1)),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntarios', to='gestion_voluntarios.emergencia')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('tiene_voluntario', models.CharField(default='0', max_length=1)),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='gestion_voluntarios.emergencia')),
                ('voluntarios', models.ManyToManyField(to='gestion_voluntarios.voluntario')),
            ],
        ),
    ]
