# Generated by Django 4.1.7 on 2023-03-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_voluntarios', '0004_remove_voluntario_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
