# Generated by Django 4.1.7 on 2023-03-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_voluntarios",
            "0006_rename_horasexperiencia_habilidad_horas_experiencia",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="voluntario",
            name="estado",
            field=models.CharField(default="D", max_length=1),
        ),
        migrations.AddField(
            model_name="voluntario",
            name="habilidades",
            field=models.CharField(default="", max_length=500),
        ),
    ]
