# Generated by Django 4.1.7 on 2023-03-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_voluntarios', '0006_rename_horasexperiencia_habilidad_horas_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='gestion_voluntarios.horario'),
        ),
    ]
