# Generated by Django 4.1.7 on 2023-03-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_voluntarios', '0007_alter_periodo_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='habilidades',
            field=models.CharField(default='', max_length=500),
        ),
    ]
