# Generated by Django 4.1.7 on 2023-03-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_voluntarios', '0007_alter_voluntario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
