# Generated by Django 4.1.7 on 2023-03-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_voluntarios", "0007_alter_periodo_horario"),
        ("gestion_voluntarios", "0007_voluntario_estado_voluntario_habilidades"),
    ]

    operations = []
