# Generated by Django 4.1.7 on 2023-03-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_voluntarios', '0008_voluntario_habilidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='habilidades',
        ),
    ]
