# Generated by Django 4.1.7 on 2023-03-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_voluntarios', '0008_alter_habilidad_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vacantes', models.IntegerField(default=0)),
                ('habilidad_requerida', models.TextField(choices=[('Suturar', 'Suturar'), ('Vacunar', 'Vacunar'), ('Anestesiar', 'Anestesiar')])),
            ],
        ),
    ]
