# Generated by Django 4.1.7 on 2023-03-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_voluntarios', '0009_remove_voluntario_habilidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='diaSemana',
            new_name='dia_semana',
        ),
        migrations.RenameField(
            model_name='periodo',
            old_name='horaFin',
            new_name='hora_fin',
        ),
        migrations.RenameField(
            model_name='periodo',
            old_name='horaInicio',
            new_name='hora_inicio',
        ),
    ]
